export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  VIEWER = 'VIEWER',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum MemberStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PROBATION = 'PROBATION',
  ALUMNI = 'ALUMNI',
}

export enum AccountType {
  GENERAL_DUES = 'GENERAL_DUES',
  EVENT_PROJECT = 'EVENT_PROJECT',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  MOBILE_MONEY = 'MOBILE_MONEY',
  PETTY_CASH = 'PETTY_CASH',
}

export enum PlanCycle {
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
}

export enum AssessmentStatus {
  UNPAID = 'UNPAID',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  SURPLUS = 'SURPLUS',
}

export enum EventStatus {
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TargetAudience {
  ALL = 'ALL',
  MEN_ONLY = 'MEN_ONLY',
  WOMEN_ONLY = 'WOMEN_ONLY',
  CUSTOM_SELECTION = 'CUSTOM_SELECTION',
}

export enum PaymentMethod {
  CASH = 'CASH',
  MOBILE_MONEY = 'MOBILE_MONEY',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CREDIT_BALANCE = 'CREDIT_BALANCE',
  OTHER = 'OTHER',
}

export enum ExpenseCategory {
  FACILITATOR_TRAINER = 'FACILITATOR_TRAINER',
  MATERIALS_SUPPLIES = 'MATERIALS_SUPPLIES',
  SOUND_EQUIPMENT = 'SOUND_EQUIPMENT',
  VENUE_LOGISTICS = 'VENUE_LOGISTICS',
  TRANSPORT = 'TRANSPORT',
  REFRESHMENTS = 'REFRESHMENTS',
  WELFARE_BENEVOLENCE = 'WELFARE_BENEVOLENCE',
  OTHER = 'OTHER',
}

export enum SessionType {
  REGULAR_MEETING = 'REGULAR_MEETING',
  COMMITTEE_MEETING = 'COMMITTEE_MEETING',
  WORKSHOP_TRAINING = 'WORKSHOP_TRAINING',
  COMMUNITY_WORK = 'COMMUNITY_WORK',
  SPECIAL_EVENT = 'SPECIAL_EVENT',
}

export enum SessionStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT_EXCUSED = 'ABSENT_EXCUSED',
  ABSENT_UNEXCUSED = 'ABSENT_UNEXCUSED',
  LATE = 'LATE',
}

export enum DebtStatus {
  ACTIVE = 'ACTIVE',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  FULLY_PAID = 'FULLY_PAID',
}

